jobs:
  - name: manifest-job-1
    type: manifest
    steps:
      - IN: box-nginx-2
      
  - name: release-job
    type: release
    bump: rc
    steps:
      - IN: manifest-job-1
      - IN: version-resource

