jobs:
        
  - name: runSh-jobQ
    type: runSh
    steps:
      - TASK:
        - script: echo "hello"
        - script: echo $(shipctl get_resource_name hello_major)
        - script: echo $(shipctl bump_version 5.1.2 major)
        - script: echo $(shipctl bump_version 5.1.2 minor)
        - script: echo $(shipctl bump_version 5.1.2 patch)
        - script: echo $(shipctl bump_version v5.1.2 major)
        - script: echo $(shipctl bump_version v5.1.2 minor)
        - script: echo $(shipctl bump_version v5.1.2 patch)
        - script: echo $(shipctl bump_version v5.1.2 rc)
        - script: echo $(shipctl bump_version v5.1.2-rc rc)
        - script: echo $(shipctl bump_version v5.1.2-rc.1 rc)
        - script: echo $(shipctl bump_version v5.1.2-rc.3 final)
        - script: echo $(shipctl bump_version v5.1.2-rc.3 alpha)
        #- script: echo $(shipctl bump_version v5.1.2-rcx.3 final)
        #- script: echo $(shipctl bump_version v5.1.2-rc.x final)
        #- script: echo $(shipctl bump_version v5.1.2 patch1)
        # script: echo $(shipctl bump_version v5.1.2x patch)

   
        
